include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_final_fields       
    - prefer_final_locals       
    - prefer_const_constructors 
    - prefer_const_declarations 
    - prefer_const_literals_to_create_immutables 
    - require_trailing_commas 

formatter:
  page_width: 90