// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:rick_and_morty_characters/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterGenderEnumAdapter());
    registerAdapter(CharacterModelAdapter());
    registerAdapter(CharactersInfoModelAdapter());
    registerAdapter(CharactersModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterGenderEnumAdapter());
    registerAdapter(CharacterModelAdapter());
    registerAdapter(CharactersInfoModelAdapter());
    registerAdapter(CharactersModelAdapter());
  }
}
